version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "8080:8080"
        env_file:
            - .env
        volumes:
            - .:/usr/src/app
        networks:
            - backend
        command: ["./entrypoint.sh", "db:5432"]
        depends_on:
            - db
    db:
        image: postgres:12-alpine
        ports:
            - "5432:5432"
        env_file:
            - .env
        volumes:
            - ./.dbcache/pg/data:/data/db
        networks:
            - backend
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
networks:
    backend:
        driver: bridge
